### PR TITLE
arithmetic-operators

### PR DESCRIPTION
**Pull request by agblaze**

### CODE REVIEW

**Comment by agblaze** [comment]
arithmetic operators by python

**Comment by syedabdr** [comment]
Please add URLs of these tasks

**Comment by agblaze** [comment]
https://www.hackerrank.com/challenges/python-arithmetic-operators/problem?isFullScreen=true

**Comment by agblaze** [comment]
https://www.hackerrank.com/challenges/python-division/problem?isFullScreen=true

**Comment by syedabdr** [comment]
These tasks have been added already.

**Pull request closed without merging**
